
name: Build and Deploy Backend to ECR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag for backend'
        required: true
        default: 'new'
        type: string

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from Git
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Docker System Prune
      run: docker system prune -f
      
    - name: Docker Container Prune  
      run: docker container prune -f
      
    - name: Build Docker Image
      run: |
        cd Application-Code/backend
        docker build -t backend:${{ github.event.inputs.tag }} .
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377240096.dkr.ecr.us-east-1.amazonaws.com
        
    - name: Tag Docker Image
      run: docker tag backend:${{ github.event.inputs.tag }} 891377240096.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.event.inputs.tag }}
        
    - name: Push Docker Image to ECR
      run: docker push 891377240096.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.event.inputs.tag }}
        
  update-deployment:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout from Git
      uses: actions/checkout@v3
      
    - name: Configure Git
      run: |
        git config user.email "javeriakashan97@gmail.com"
        git config user.name "javeriakhn"
        
    - name: Update Deployment File
      run: |
        cd Kubernetes-Manifests-file/Backend
        echo "Current deployment.yaml content before modification:"
        cat deployment.yaml
        # Extract the current image tag and update it with the new tag
        imageTag=$(grep -oP '(?<=backend:)\S+' deployment.yaml)
        echo "Parsed imageTag=${imageTag}"
        # Update the image tag in deployment.yaml
        sed -i "s/backend:${imageTag}/backend:${{ github.event.inputs.tag }}/g" deployment.yaml
        echo "Updated deployment.yaml content after modification:"
        cat deployment.yaml
        # Commit and push changes
        git add deployment.yaml
        git commit -m "Update backend deployment image to version ${{ github.event.inputs.tag }}"
        
    - name: Push Changes to Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git pull --rebase origin master
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
        
    - name: Cleanup Workspace
      run: |
        git clean -dfx
        git reset --hard




